//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionTreeEntropyGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DecisionTreeEntropyGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DataSet&gt;
        ///  &lt;Schema&gt;
        ///    &lt;Attributes&gt;
        ///      &lt;Attribute Identifier=&quot;True&quot;&gt;Visitor&lt;/Attribute&gt;
        ///      &lt;Attribute Queryable=&quot;True&quot;&gt;Referrer&lt;/Attribute&gt;
        ///      &lt;Attribute Queryable=&quot;True&quot;&gt;Frequency&lt;/Attribute&gt;
        ///      &lt;Attribute Queryable=&quot;True&quot;&gt;Search&lt;/Attribute&gt;
        ///      &lt;Attribute Queryable=&quot;True&quot;&gt;Length&lt;/Attribute&gt;
        ///    &lt;/Attributes&gt;
        ///    &lt;Answers&gt;
        ///      &lt;Answer&gt;Yes&lt;/Answer&gt;
        ///      &lt;Answer&gt;No&lt;/Answer&gt;
        ///    &lt;/Answers&gt;
        ///  &lt;/Schema&gt;
        ///  &lt;Data&gt;
        ///    &lt;Datum Answer=&quot;No&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssignmentData {
            get {
                return ResourceManager.GetString("AssignmentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DataSet&gt;
        ///  &lt;Schema&gt;
        ///    &lt;Attributes&gt;
        ///      &lt;Attribute Identifier=&quot;True&quot;&gt;ID&lt;/Attribute&gt;
        ///      &lt;Attribute&gt;Name&lt;/Attribute&gt;
        ///      &lt;Attribute Queryable=&quot;True&quot;&gt;Genre&lt;/Attribute&gt;
        ///      &lt;Attribute Queryable=&quot;True&quot;&gt;Decade&lt;/Attribute&gt;
        ///      &lt;Attribute Queryable=&quot;True&quot;&gt;Format&lt;/Attribute&gt;
        ///      &lt;Attribute Queryable=&quot;True&quot;&gt;Rating&lt;/Attribute&gt;
        ///    &lt;/Attributes&gt;
        ///    &lt;Answers&gt;
        ///      &lt;Answer&gt;Yes&lt;/Answer&gt;
        ///      &lt;Answer&gt;No&lt;/Answer&gt;
        ///    &lt;/Answers&gt;
        ///  &lt;/Schema&gt;
        ///  &lt;Data&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MovieData {
            get {
                return ResourceManager.GetString("MovieData", resourceCulture);
            }
        }
    }
}
